# Generated by Django 4.1.2 on 2022-11-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorid', models.CharField(max_length=64, verbose_name='센서아이디')),
                ('ownername', models.CharField(max_length=64, verbose_name='소유주/상호')),
                ('ownerid', models.CharField(max_length=64, verbose_name='관리자아이디')),
                ('status', models.CharField(max_length=64, verbose_name='센서상태')),
                ('category', models.CharField(max_length=64, verbose_name='센서구분')),
                ('address1', models.TextField(verbose_name='시/군/구')),
                ('address2', models.TextField(verbose_name='주소')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
            ],
            options={
                'verbose_name': '센서',
                'verbose_name_plural': '센서',
                'db_table': 'powermon_sensor',
            },
        ),
    ]
