# Generated by Django 4.1.2 on 2023-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='address3',
            field=models.TextField(default='수전실', verbose_name='설치위치'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensor',
            name='address2',
            field=models.TextField(verbose_name='상세주소'),
        ),
    ]
