# Generated by Django 4.1.2 on 2022-10-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.CharField(blank=True, max_length=64, verbose_name='센서아이디')),
                ('channel_name', models.CharField(blank=True, max_length=64, verbose_name='채널이름')),
                ('channel_status', models.CharField(blank=True, max_length=64, verbose_name='채널상태')),
                ('sensor_status', models.CharField(blank=True, max_length=64, verbose_name='센서상태')),
                ('transaction_id', models.CharField(blank=True, max_length=256, verbose_name='트랜젝션아이디')),
            ],
            options={
                'verbose_name': '센서상태',
                'verbose_name_plural': '센서상태',
                'db_table': 'powermon_clients',
            },
        ),
    ]
