# Generated by Django 4.1.5 on 2023-02-14 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('sensor', '0002_sensor_address3_alter_sensor_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_target', models.IntegerField(verbose_name='피크목표')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('sensorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensor.sensor', verbose_name='센서아이디')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='회원아이디')),
            ],
            options={
                'verbose_name': '운용변수',
                'verbose_name_plural': '운용변수',
                'db_table': 'powermon_variables',
            },
        ),
    ]
