# Generated by Django 4.1.2 on 2022-10-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_name', models.CharField(max_length=64, verbose_name='메세지이름')),
                ('sensor_id', models.CharField(max_length=64, verbose_name='센서아이디')),
                ('transaction_id', models.CharField(max_length=256, verbose_name='트랜젝션아이디')),
                ('timestamp', models.DateTimeField(verbose_name='생성일시')),
                ('data', models.TextField(verbose_name='메세지본문')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '메세지정보',
                'verbose_name_plural': '메세지정보',
                'db_table': 'powermon_item',
            },
        ),
    ]
