# Generated by Django 4.1.5 on 2023-02-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='msg_direction',
            field=models.IntegerField(default=2, verbose_name='메세지디렉션'),
            preserve_default=False,
        ),
    ]
