# Generated by Django 4.1.2 on 2022-11-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energyinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensorid', models.CharField(max_length=64, verbose_name='센서아이디')),
                ('probeid', models.IntegerField(verbose_name='프루브아이디')),
                ('m_time', models.DateTimeField(verbose_name='측정일시')),
                ('energy', models.IntegerField(verbose_name='전력량')),
                ('pf', models.IntegerField(verbose_name='파워팩터')),
                ('voltage', models.IntegerField(verbose_name='전압')),
                ('register_dttm', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '에너지정보',
                'verbose_name_plural': '에너지정보',
                'db_table': 'powermon_energyinfo',
            },
        ),
    ]
