# Generated by Django 4.1.5 on 2023-02-02 03:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('energyinfo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyinfo',
            name='m_time',
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='m_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='m_hour',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='시간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='m_minute',
            field=models.CharField(default='q1', max_length=64, verbose_name='분대역구분'),
            preserve_default=False,
        ),
    ]
