# Generated by Django 4.1.5 on 2023-02-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyinfo', '0002_remove_energyinfo_m_time_energyinfo_m_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyinfo',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='energyinfo',
            name='pf',
        ),
        migrations.RemoveField(
            model_name='energyinfo',
            name='probeid',
        ),
        migrations.RemoveField(
            model_name='energyinfo',
            name='voltage',
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='energy_a',
            field=models.IntegerField(default=0, verbose_name='A전력량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='energy_b',
            field=models.IntegerField(default=0, verbose_name='B전력량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='energy_c',
            field=models.IntegerField(default=0, verbose_name='C전력량'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='pf_a',
            field=models.IntegerField(default=0, verbose_name='A파워팩터'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='pf_b',
            field=models.IntegerField(default=0, verbose_name='B파워팩터'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='pf_c',
            field=models.IntegerField(default=0, verbose_name='C파워팩터'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='voltage_a',
            field=models.IntegerField(default=220, verbose_name='A전압'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='voltage_b',
            field=models.IntegerField(default=220, verbose_name='B전압'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='energyinfo',
            name='voltage_c',
            field=models.IntegerField(default=220, verbose_name='C전압'),
            preserve_default=False,
        ),
    ]
