# Generated by Django 4.1.5 on 2023-02-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energyinfo', '0003_remove_energyinfo_energy_remove_energyinfo_pf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyinfo',
            name='m_date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='energyinfo',
            name='m_hour',
            field=models.IntegerField(verbose_name='시간'),
        ),
    ]
